build:
    environment:
        php:
            version: 7.2
    nodes:
        coverage:
            tests:
                override:
                    -   command: |
                            php -r "file_exists('.env') || copy('.env.example', '.env');"
                            php yii generate/key
                            vendor/bin/codecept build
                            php yii migrate --interactive=0
                            vendor/bin/codecept run --coverage --coverage-xml
                        coverage:
                            file: tests\_output\coverage.xml
                            format: clover
filter:
    excluded_paths:
        - ./web/*
        - ./migrations/*,
        - ./vendor/*
        - ./runtime/*
        - ./requirements.php

checks:
    php:
        code_rating: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
tools:
    external_code_coverage:
        timeout: 600
        runs: 3
    php_analyzer: true
    php_code_coverage:
        enabled: true
